### ISSUE TITLE
Add schema for Kustomization

### ISSUE THREAD

**Issue by MPV** [SAP/ytt-lint#2]
Would you be open to adding schema for `Kustomization`?

As `kind: Kustomization` is a part of kubernetes (at least via kubectl).

I currently get this warning on these kinds of manifests:

>Error loading schema for kind Kustomization: could not find schema file k8s/kustomize.config.k8s.io/v1beta1/kustomization.json in: [/Users/myself/.ytt-lint/schema /Users/myself/.vscode/extensions/phil9909.ytt-lint-0.2.0/schema]

...on a manifest with:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# [...]
```
